# Exercise - Create a workflow that deploys a web app to Azure

name: Stage the app

# Filters the workflow triggers to a label present
on:
  pull_request:
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
